# Generated by Django 4.1.3 on 2022-12-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_company_foundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='direccion',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
