# Generated by Django 4.1.3 on 2022-12-01 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_company_direccion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company',
            new_name='provedores',
        ),
    ]
