# Generated by Django 4.1.3 on 2022-12-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_company_provedores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=200)),
                ('codigo_barra', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('unidadesEnStock', models.IntegerField()),
                ('precioUnitario', models.FloatField(default=0)),
            ],
        ),
    ]
