# Generated by Django 4.1.3 on 2022-12-04 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_servicio_remove_provedores_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='provedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.provedores'),
        ),
    ]
